global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gap-arcade'
    metrics_path: '/healthz'
    static_configs:
      - targets: ['localhost:8080']
        labels:
          app: 'gap-arcade'
          env: 'production'
