apiVersion: v1
kind: Service
metadata:
  name: gap-arcade-service
  labels:
    app.kubernetes.io/name: gap-arcade
spec:
  type: LoadBalancer # Change to NodePort or ClusterIP depending on environment
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: gap-arcade
